<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup Label="framework_references">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup Label="package_references">
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup Label="sqlite_packages">
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageReference Include="SQLitePCLRaw.config.e_sqlite3" Version="3.0.3" />
    <PackageReference Include="SQLitePCLRaw.core" Version="3.0.3" />
    <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="3.0.3" />
  </ItemGroup>

  <ItemGroup Label="project_references">
    <ProjectReference Include="..\Teams.Domain\Teams.Domain.csproj" />
  </ItemGroup>

  <ItemGroup Label="visibility_modifiers">
    <InternalsVisibleTo Include="Teams.Data.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Context\Migrations\" />
  </ItemGroup>

</Project>
