// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teams.Data.Context;

#nullable disable

namespace Teams.Data.Context.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260802080801_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Teams.Domain.Entities.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int?>("AwayTeamRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("away_rating");

                    b.Property<long>("Cursor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cursor");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_deleted");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_modified");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("minutes");

                    b.Property<int?>("HomeTeamRating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("home_rating");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("TeamSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("team_size");

                    b.Property<int?>("Winner")
                        .HasColumnType("INTEGER")
                        .HasColumnName("winner");

                    b.HasKey("Id");

                    b.HasIndex("Cursor")
                        .IsUnique();

                    b.HasIndex("DateCreated");

                    b.HasIndex("DateDeleted");

                    b.HasIndex("DateModified");

                    b.ToTable("game", (string)null);
                });

            modelBuilder.Entity("Teams.Domain.Entities.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("Cursor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cursor");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_deleted");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_modified");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("game_id");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rating");

                    b.Property<int?>("RatingChange")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delta");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER")
                        .HasColumnName("team");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Cursor")
                        .IsUnique();

                    b.HasIndex("DateCreated");

                    b.HasIndex("DateDeleted");

                    b.HasIndex("DateModified");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Teams.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("Cursor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cursor");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_deleted");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_modified");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("idp_id");

                    b.Property<string>("Mobile")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rating");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("tag");

                    b.HasKey("Id");

                    b.HasIndex("Cursor")
                        .IsUnique();

                    b.HasIndex("DateCreated");

                    b.HasIndex("DateDeleted");

                    b.HasIndex("DateModified");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Teams.Domain.Entities.Player", b =>
                {
                    b.HasOne("Teams.Domain.Entities.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teams.Domain.Entities.User", "User")
                        .WithMany("Participation")
                        .HasForeignKey("UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Teams.Domain.Entities.Game", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Teams.Domain.Entities.User", b =>
                {
                    b.Navigation("Participation");
                });
#pragma warning restore 612, 618
        }
    }
}
