<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Teams.Common\Teams.Common.csproj" />
    <InternalsVisibleTo Include="Teams.Domain.UnitTests" />
  </ItemGroup>

</Project>
